# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='text',
            field=models.TextField(default=True),
        ),
    ]
