# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-27 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_area', '0002_privacypolicy_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='text',
            field=models.TextField(),
        ),
    ]
