# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20170701_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForRepairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=True, max_length=128, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=True, max_digits=10)),
                ('discount', models.IntegerField(default=0)),
                ('price_with_discount', models.DecimalField(decimal_places=2, default=True, max_digits=10)),
                ('short_description', models.TextField(blank=True, default=None, max_length=50, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory')),
            ],
            options={
                'verbose_name': 'Для ремонта',
                'verbose_name_plural': 'Для ремонта',
            },
        ),
    ]
